### ISSUE TITLE
My working copy of nativescript-app-encryption

### ISSUE THREAD

**Issue by zenz** [NativeScript/nativescript-app-encryption#11]
As title, here's my working copy of nativescript-app-encryption

just use
tns plugin add https://github.com/zenz/nativescript-app-encryption.git
to add my plugin into your project. And do
tns build ios|android --release [--for-device]
will do the rest of the works.

**Comment by almorabet** [comment]
that works perfectly, thanks for the precious effort

my question is how to use app-encryp with webpack, i mean encrypt the code after minification ?

**Comment by zenz** [comment]
It's not compatible with Webpack yet. It prepare the encrypted js files before webpack handling, so it will failed while webpack doing it's job(some not exist files).

**Comment by almorabet** [comment]
yeh, thanks for response. hoping to improve that plugin, it's a great tool
